# ---------------------------------------------------------------------------
# Outputs + auto-generated python/.env so the producer needs no manual wiring.
# ---------------------------------------------------------------------------

output "environment_id" {
  description = "Confluent Cloud environment ID."
  value       = confluent_environment.main.id
}

output "kafka_cluster_id" {
  description = "Kafka cluster ID."
  value       = confluent_kafka_cluster.main.id
}

output "kafka_bootstrap_endpoint" {
  description = "Kafka bootstrap servers (host:port) for the producer."
  value       = confluent_kafka_cluster.main.bootstrap_endpoint
}

output "schema_registry_id" {
  description = "Schema Registry cluster ID."
  value       = data.confluent_schema_registry_cluster.main.id
}

output "schema_registry_rest_endpoint" {
  description = "Schema Registry REST endpoint."
  value       = data.confluent_schema_registry_cluster.main.rest_endpoint
}

output "flink_compute_pool_id" {
  description = "Flink compute pool ID."
  value       = confluent_flink_compute_pool.main.id
}

output "flink_rest_endpoint" {
  description = "Flink REST endpoint for the region."
  value       = data.confluent_flink_region.main.rest_endpoint
}

output "service_account_id" {
  description = "Service account ID owning the keys."
  value       = confluent_service_account.app.id
}

# Bootstrap endpoint arrives as SASL_SSL://host:port; the client wants host:port.
locals {
  bootstrap_host = replace(confluent_kafka_cluster.main.bootstrap_endpoint, "SASL_SSL://", "")
}

resource "local_sensitive_file" "producer_env" {
  filename = "${path.module}/../python/.env"

  content = <<-EOT
    # Auto-generated by Terraform. Do not commit. Regenerated on every apply.
    KAFKA_BOOTSTRAP_SERVERS=${local.bootstrap_host}
    KAFKA_API_KEY=${confluent_api_key.kafka.id}
    KAFKA_API_SECRET=${confluent_api_key.kafka.secret}

    SCHEMA_REGISTRY_URL=${data.confluent_schema_registry_cluster.main.rest_endpoint}
    SCHEMA_REGISTRY_API_KEY=${confluent_api_key.schema_registry.id}
    SCHEMA_REGISTRY_API_SECRET=${confluent_api_key.schema_registry.secret}

    TOPIC=transactions
  EOT
}
